[package]
name = "notification-emitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
serde = "1.0.185"
serde_derive = "1.0.185"
zbus = "3.14.1"
